#!/usr/bin/env python3
"""Generate the vector CISA marks in assets/.

  assets/cisa-logo.svg      the original CISA badge, redrawn as a pure vector
  assets/seal-ring.svgfrag  ring lettering for the "ci seal" (from the CISA logo
                            concepts canvas), as outlines with a {{FG}} fill placeholder

All lettering is converted to outline paths with fontTools and laid out glyph by
glyph along arcs, so nothing needs fonts at render time and every SVG renderer
(including librsvg, which has no <textPath>) draws it identically.

Needs: python3-fonttools, fonts-montserrat, fonts-jetbrains-mono.
Run:   python3 dev/make-logo.py
"""
import math
import pathlib

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ASSETS = pathlib.Path(__file__).resolve().parent.parent / "assets"


class Font:
    def __init__(self, path):
        self.tt = TTFont(path)
        self.glyphs = self.tt.getGlyphSet()
        self.cmap = self.tt.getBestCmap()
        self.upem = self.tt["head"].unitsPerEm
        self.hmtx = self.tt["hmtx"]
        self.cap = self.tt["OS/2"].sCapHeight / self.upem

    def width(self, ch, size):
        return self.hmtx[self.cmap[ord(ch)]][0] / self.upem * size


def arc_text(font, text, radius, mid_deg, size, spacing, outward_up, fill,
             cx=500.0, cy=500.0, fit_deg=None):
    """Lay out `text` centred on `mid_deg` (screen degrees: 0 = right, 90 = down).

    outward_up=True : letters stand on the circle, tops outward (reads clockwise).
    outward_up=False: letters hang inside, tops toward the centre (reads counter-clockwise).
    `radius` is where the letters' vertical centre sits. With `fit_deg`, the letter
    spacing is chosen so the text spans exactly that many degrees.
    """
    base_r = radius - font.cap * size / 2 if outward_up else radius + font.cap * size / 2
    widths = [font.width(c, size) for c in text]
    if fit_deg is not None:
        spacing = (math.radians(fit_deg) * base_r - sum(widths)) / (len(text) - 1)
    total = sum(widths) + spacing * (len(text) - 1)
    direction = 1 if outward_up else -1
    theta = math.radians(mid_deg) - direction * (total / base_r) / 2
    s = size / font.upem
    parts = []
    for ch, w in zip(text, widths):
        centre = theta + direction * (w / 2) / base_r
        if ch != " ":
            x = cx + base_r * math.cos(centre)
            y = cy + base_r * math.sin(centre)
            rot = centre + (math.pi / 2 if outward_up else -math.pi / 2)
            c, sn = math.cos(rot), math.sin(rot)
            # glyph space (y up): scale, flip y, centre the advance, rotate, move onto the arc
            matrix = (s * c, s * sn, s * sn, -s * c, x - (w / 2) * c, y - (w / 2) * sn)
            pen = SVGPathPen(font.glyphs)
            font.glyphs[font.cmap[ord(ch)]].draw(TransformPen(pen, matrix))
            parts.append(pen.getCommands())
        theta += direction * (w + spacing) / base_r
    return f'<path fill="{fill}" d="{" ".join(parts)}"/>'


def badge():
    f = Font("/usr/share/fonts/opentype/montserrat/Montserrat-ExtraBold.otf")
    ink = "#0b0f14"
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1000" width="1000" height="1000">
  <!-- CISA badge, Cybersecurity & IT Student Association, Penn State Abington.
       Generated by dev/make-logo.py: a pure vector (lettering converted to outlines). -->
  <defs>
    <linearGradient id="shield-fill" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#2f6cc4"/>
      <stop offset="1" stop-color="#2459a8"/>
    </linearGradient>
  </defs>

  <circle cx="500" cy="500" r="484" fill="{ink}"/>
  <circle cx="500" cy="500" r="462" fill="#ffffff"/>
  <circle cx="500" cy="500" r="345" fill="{ink}"/>

  {arc_text(f, "CYBERSECURITY & IT", 402, 274, 72, 4, True, ink)}
  {arc_text(f, "STUDENT ASSOCIATION", 400, 90, 72, 4, False, ink)}

  <g fill="none" stroke="#3b7dd8" stroke-width="9" stroke-linecap="round" stroke-linejoin="round">
    <path d="M 150 466 H 226 L 250 448 H 300"/>
    <path d="M 126 500 H 300"/>
    <path d="M 150 534 H 226 L 250 552 H 300"/>
    <path d="M 196 584 H 236 L 258 602 H 312"/>
  </g>
  <g fill="#ffffff" stroke="#3b7dd8" stroke-width="7">
    <circle cx="150" cy="466" r="12"/>
    <circle cx="126" cy="500" r="12"/>
    <circle cx="150" cy="534" r="12"/>
    <circle cx="196" cy="584" r="12"/>
  </g>

  <path d="M 500 214 C 572 254 642 266 716 266 L 716 452 C 716 592 622 684 500 742 C 378 684 284 592 284 452 L 284 266 C 358 266 428 254 500 214 Z"
        fill="url(#shield-fill)" stroke="#ffffff" stroke-width="22" stroke-linejoin="round"/>

  <path d="M 452 440 V 392 A 48 48 0 0 1 548 392 V 440" fill="none" stroke="#ffffff" stroke-width="32"/>
  <rect x="394" y="430" width="212" height="168" rx="20" fill="#ffffff"/>
  <circle cx="500" cy="496" r="22" fill="#0d1b2e"/>
  <path d="M 490 506 L 484 560 H 516 L 510 506 Z" fill="#0d1b2e"/>

  <path d="M 279.3 914.9 A 470 470 0 0 0 720.7 914.9" fill="none" stroke="#ffffff" stroke-width="60"/>
  <path d="M 279.3 914.9 A 470 470 0 0 0 720.7 914.9" fill="none" stroke="{ink}" stroke-width="48"/>
  {arc_text(f, "PENN STATE ABINGTON", 470, 90, 27, 2.5, False, "#ffffff")}
</svg>
'''


def seal_ring():
    """Ring lettering for the ci seal, in a 400x400 box centred at (200, 200)."""
    f = Font("/usr/share/fonts/truetype/jetbrains-mono/JetBrainsMono-Medium.ttf")
    top = arc_text(f, "CYBERSECURITY & IT · STUDENT ASSOCIATION", 148, 270, 18, 0, True,
                   "{{FG}}", cx=200, cy=200, fit_deg=226)
    bottom = arc_text(f, "PENN STATE ABINGTON", 150, 90, 18, 3.2, False, "{{FG}}", cx=200, cy=200)
    return f"<!-- generated by dev/make-logo.py -->\n{top}\n{bottom}\n"


for name, content in (("cisa-logo.svg", badge()), ("seal-ring.svgfrag", seal_ring())):
    out = ASSETS / name
    out.write_text(content)
    print(f"wrote {out} ({out.stat().st_size // 1024} KB)")
