"""CISA Rice: generate every app config from a theme palette.

Each function returns {relative path under ~/.config: file content}. The look is
one design language (boxed monospace modules, thin borders, TUI widgets) in four
styles: solid, glass (frosted + glossy), oled (true black, no glow), blueprint
(monochrome, boxed, like the reference rice).
"""
import json

from art import hex_rgb, mix, on, rgba

FONT = "JetBrains Mono"
ICON_FONT = "FontAwesome"          # fonts-font-awesome (4.7) - every glyph below exists there

# Font Awesome 4.7 glyphs
I = {
    "power": "", "apps": "", "brush": "", "cpu": "", "mem": "", "disk": "",
    "temp": "", "wifi": "", "eth": "", "off": "", "vol": "", "mute": "",
    "mic": "", "bat": ["", "", "", "", ""], "plug": "", "shield": "",
    "lock": "", "clock": "", "bell": "", "term": "", "search": "", "key": "",
    "logout": "", "moon": "", "refresh": "", "grid": "",
}


def hy(h, alpha=1.0):
    """Hyprland colour: rgba(rrggbbaa)."""
    return f"rgba({h.lstrip('#')}{round(alpha * 255):02x})"


def term_colors(t):
    if t["DARK"]:
        black, white = mix(t["BG"], "#000000", 35), mix(t["FG"], t["BG"], 12)
        bblack, bwhite = t["MUTED"], t["FG"]
    else:
        black, white = t["FG"], mix(t["BG"], "#000000", 12)
        bblack, bwhite = t["MUTED"], mix(t["BG"], "#000000", 4)
    base = [black, t["RED"], t["GREEN"], t["YELLOW"], t["BLUE"], t["MAGENTA"], t["CYAN"], white]
    bright = [bblack] + [mix(c, "#ffffff" if t["DARK"] else "#000000", 18) for c in base[1:7]] + [bwhite]
    return base + bright


# --------------------------------------------------------------------------- Hyprland

def hyprland(t, d):
    s = t["STYLE"]
    if s == "glass":
        active = f"{hy('#ffffff', .85)} {hy(t['ACCENT'], .55)} {hy('#ffffff', .25)} 45deg"
        inactive = hy("#ffffff", .18)
        blur = "size = 9\n        passes = 4\n        vibrancy = 0.32\n        noise = 0.015\n        brightness = 1.05\n        contrast = 1.0"
        shadow = f"enabled = true\n        range = 28\n        render_power = 3\n        color = {hy('#000000', .45)}"
    elif s == "oled":
        active = hy(t["FG"], .55)
        inactive = hy(t["LINE"])
        blur = "size = 1\n        passes = 1"
        shadow = "enabled = false"
    elif s == "blueprint":
        active = f"{hy('#ffffff')} {hy('#646464')} 45deg"
        inactive = hy("#ffffff", .3)
        blur = "size = 5\n        passes = 3\n        vibrancy = 0.17"
        shadow = f"enabled = true\n        range = 5\n        render_power = 3\n        color = {hy('#1a1a1a')}"
    else:
        active = f"{hy(t['ACCENT'])} {hy(t['FG'], .9)} 45deg"
        inactive = hy(t["LINE"])
        blur = "size = 6\n        passes = 3\n        vibrancy = 0.2"
        shadow = f"enabled = true\n        range = 14\n        render_power = 3\n        color = {hy('#000000', .4 if t['DARK'] else .14)}"
    inactive_op = 1.0 if s == "oled" else max(0.6, float(t["WIN_OPACITY"]) - 0.08)
    return {"hypr/hyprland.conf": f"""# CISA Rice: Hyprland, theme "{t['NAME']}". Generated by cisa-rice; re-run it instead of editing.
# Your own tweaks go in ~/.config/hypr/user.conf (never overwritten).

monitor = , preferred, auto, 1

$terminal = kitty
$files = dolphin
$browser = firefox-esr
$menu = fuzzel

# ---------- autostart
# Waybar is supervised: restarted whenever it exits (it can fail very early in a session),
# logged to $XDG_RUNTIME_DIR/waybar.log. Theme changes reload it in place with SIGUSR2.
exec-once = cisa-bar
exec-once = swaync
exec-once = swaybg -i {d}/wallpaper.png -m fill
exec-once = hypridle
exec-once = systemctl --user start hyprpolkitagent || /usr/libexec/hyprpolkitagent || /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = nm-applet --indicator
exec-once = wl-paste --watch cliphist store
exec-once = cisa-dashboard --first-login
exec = gsettings set org.gnome.desktop.interface color-scheme '{'prefer-dark' if t['DARK'] else 'prefer-light'}'
exec = gsettings set org.gnome.desktop.interface gtk-theme '{'Breeze-Dark' if t['DARK'] else 'Breeze'}'
exec = gsettings set org.gnome.desktop.interface icon-theme '{t['ICONS']}'
exec = gsettings set org.gnome.desktop.interface cursor-theme '{t['CURSOR']}'
exec = gsettings set org.gnome.desktop.interface monospace-font-name '{FONT} 11'
exec = hyprctl setcursor {t['CURSOR']} 24

# ---------- environment
env = XCURSOR_THEME,{t['CURSOR']}
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,kde
env = QT_QPA_PLATFORM,wayland;xcb
env = GDK_BACKEND,wayland,x11
env = MOZ_ENABLE_WAYLAND,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

# ---------- look and feel
general {{
    gaps_in = {t['GAPS_IN']}
    gaps_out = {t['GAPS_OUT']}
    border_size = {t['BORDER']}
    col.active_border = {active}
    col.inactive_border = {inactive}
    resize_on_border = true
    layout = dwindle
}}

decoration {{
    rounding = {t['RADIUS']}
    active_opacity = {t['WIN_OPACITY']}
    inactive_opacity = {inactive_op:.2f}
    dim_inactive = {'false' if s == 'oled' else 'true'}
    dim_strength = 0.06

    shadow {{
        {shadow}
    }}

    blur {{
        enabled = {'true' if t['BLUR'] else 'false'}
        {blur}
        popups = true
    }}
}}

animations {{
    enabled = yes
    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    bezier = quick, 0.15, 0, 0.1, 1
    bezier = almostLinear, 0.5, 0.5, 0.75, 1.0
    animation = global, 1, 10, default
    animation = windows, 1, 4.8, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
    animation = windowsOut, 1, 1.5, almostLinear, popin 87%
    animation = border, 1, 5.4, easeOutQuint
    animation = fade, 1, 3, quick
    animation = layers, 1, 3.8, easeOutQuint
    animation = layersIn, 1, 4, easeOutQuint, fade
    animation = workspaces, 1, 2.2, almostLinear, slidefade 12%
}}

dwindle {{
    preserve_split = true
}}

misc {{
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    background_color = {hy(t['BG'])}
}}

cursor {{
    no_hardware_cursors = true
}}

input {{
    kb_layout = us
    follow_mouse = 1
    touchpad {{
        natural_scroll = false
        tap-to-click = true
    }}
}}

source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/user.conf
""", "hypr/binds.conf": BINDS, "hypr/rules.conf": RULES}


# Windows-familiar where it can be: Super opens the menu, Alt+F4 closes, Alt+Tab switches,
# Win+L locks, Win+E files, Win+V clipboard, Win+Shift+S / Print screenshot, Win+X power menu.
BINDS = """# CISA Rice key bindings (Super = the Windows key). Super+/ shows this list on screen.
$mod = SUPER

bindr = $mod, SUPER_L, exec, cisa-menu
bind = $mod, SPACE, exec, cisa-menu
bind = $mod, RETURN, exec, kitty
bind = $mod, T, exec, kitty
bind = $mod, E, exec, dolphin
bind = $mod, B, exec, firefox-esr
bind = $mod, D, exec, cisa-dashboard
bind = $mod, SLASH, exec, cisa-keys
bind = $mod SHIFT, T, exec, cisa-theme
bind = $mod, N, exec, swaync-client -t -sw
bind = $mod, V, exec, cisa-clip
bind = $mod, C, exec, hyprpicker -a
bind = $mod, L, exec, loginctl lock-session
bind = $mod, X, exec, cisa-power
bind = $mod, ESCAPE, exec, cisa-power

bind = ALT, F4, killactive
bind = $mod, Q, killactive
bind = $mod, W, togglefloating
bind = $mod, F, fullscreen, 0
bind = $mod, M, fullscreen, 1
bind = $mod, J, layoutmsg, togglesplit
bind = $mod, P, pseudo
bind = ALT, TAB, cyclenext
bind = ALT, TAB, bringactivetotop

bind = , PRINT, exec, cisa-shot region
bind = $mod SHIFT, S, exec, cisa-shot region
bind = SHIFT, PRINT, exec, cisa-shot screen

bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d
bind = $mod SHIFT, left, movewindow, l
bind = $mod SHIFT, right, movewindow, r
bind = $mod SHIFT, up, movewindow, u
bind = $mod SHIFT, down, movewindow, d
binde = $mod CTRL, left, resizeactive, -40 0
binde = $mod CTRL, right, resizeactive, 40 0
binde = $mod CTRL, up, resizeactive, 0 -40
binde = $mod CTRL, down, resizeactive, 0 40

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod, S, togglespecialworkspace, scratch
bind = $mod ALT, S, movetoworkspace, special:scratch
bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up, workspace, e-1
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = , XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPrev, exec, playerctl previous
"""

RULES = """# Window and layer rules (Hyprland 0.53+ syntax).
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol|pavucontrol-qt|nm-connection-editor|blueman-manager)$
windowrule = float on, match:class ^(org.kde.polkit-kde-authentication-agent-1|hyprpolkitagent)$
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = suppress_event maximize, match:class .*

layerrule = blur on, match:namespace ^(waybar|swaync-control-center|swaync-notification-window|launcher|logout_dialog|cisa-menu)$
layerrule = ignore_alpha 0.36, match:namespace ^(waybar|swaync-control-center|swaync-notification-window|launcher|logout_dialog|cisa-menu)$
layerrule = animation popin 94%, match:namespace ^(cisa-menu|launcher)$
"""


def hyprlock(t, d):
    s = t["STYLE"]
    blur = 0 if s in ("oled", "blueprint") else (3 if s == "glass" else 2)
    field_bg = hy("#000000") if s == "oled" else hy(t["BG"], .55 if s == "glass" else .85)
    return {"hypr/hyprlock.conf": f"""# CISA Rice lock screen ({t['NAME']})
general {{
    hide_cursor = true
    grace = 0
}}

background {{
    monitor =
    path = {d}/lock.png
    blur_passes = {blur}
    blur_size = 6
    brightness = {0.85 if t['DARK'] else 1.0}
}}

label {{
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = {hy(t['FG'])}
    font_size = 110
    font_family = {FONT} ExtraBold
    position = 0, 260
    halign = center
    valign = center
}}

label {{
    monitor =
    text = cmd[update:60000] date +"%A, %B %-d" | tr '[:upper:]' '[:lower:]'
    color = {hy(t['MUTED'])}
    font_size = 18
    font_family = {FONT}
    position = 0, 160
    halign = center
    valign = center
}}

input-field {{
    monitor =
    size = 340, 54
    outline_thickness = 2
    rounding = {min(t['RADIUS'], 12)}
    outer_color = {hy(t['FG'], .9)}
    inner_color = {field_bg}
    font_color = {hy(t['FG'])}
    check_color = {hy(t['ACCENT'])}
    fail_color = {hy(t['RED'])}
    fade_on_empty = false
    placeholder_text = <span foreground="##{t['MUTED'].lstrip('#')}">password for $USER</span>
    fail_text = wrong password ($ATTEMPTS)
    dots_size = 0.22
    dots_spacing = 0.35
    font_family = {FONT}
    position = 0, -260
    halign = center
    valign = center
}}

label {{
    monitor =
    text = learn to hack. the legal way.
    color = {hy(t['MUTED'])}
    font_size = 12
    font_family = {FONT}
    position = 0, 40
    halign = center
    valign = bottom
}}
"""}


def hypridle(t, d):
    return {"hypr/hypridle.conf": """# Lock after 5 min, screen off after 10, lock before sleep.
general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
"""}


# --------------------------------------------------------------------------- shared surfaces

def surface(t):
    """One visual language for every floating surface (bar islands, menu card, launcher):
    background, border, shadow, radius and text colours per style."""
    s = t["STYLE"]
    if s == "glass":
        return dict(bg="rgba(16, 22, 44, 0.42)", bg_solid="rgba(16,22,44,0.92)", border="rgba(255, 255, 255, 0.22)",
                    sheen="linear-gradient(180deg, rgba(255,255,255,0.16), rgba(255,255,255,0.02) 60%)",
                    shadow="0 8px 28px rgba(0,0,0,0.35), inset 0 1px 0 rgba(255,255,255,0.25)", radius=16,
                    fg="#ffffff", muted="rgba(255,255,255,0.62)", hover="rgba(255,255,255,0.12)",
                    active="rgba(255,255,255,0.20)", field="rgba(255,255,255,0.10)", bw=1)
    if s == "oled":
        return dict(bg="#000000", bg_solid="#000000", border=t["LINE"], sheen="none", shadow="none", radius=10,
                    fg=t["FG"], muted=t["MUTED"], hover="#0b0e13", active="#12161d", field="#07090c", bw=1)
    if s == "blueprint":
        return dict(bg="rgba(5, 5, 5, 0.86)", bg_solid="#050505", border="rgba(255,255,255,0.85)", sheen="none",
                    shadow="none", radius=0, fg="#f2f2f2", muted="#8a8a8a", hover="rgba(255,255,255,0.08)",
                    active="#f2f2f2", field="rgba(255,255,255,0.05)", bw=1)
    dark = t["DARK"]
    return dict(bg=rgba(t["SURFACE"], .86 if dark else .9), bg_solid=t["SURFACE"],
                border=rgba(t["FG"], .12 if dark else .14), sheen="none",
                shadow=f"0 8px 24px {rgba('#000000', .32 if dark else .10)}", radius=min(max(t['RADIUS'], 8), 14),
                fg=t["FG"], muted=t["MUTED"], hover=rgba(t["FG"], .07), active=rgba(t["FG"], .12),
                field=rgba(t["FG"], .06 if dark else .05), bw=1)


# --------------------------------------------------------------------------- Waybar

def waybar(t, d):
    """Minimal bar: three floating islands. Left: CISA mark (menu) + workspace dots.
    Centre: clock. Right: lab VPN, network, volume, battery, tray, power."""
    cfg = {
        "layer": "top", "position": "top", "height": 34, "spacing": 0,
        "margin-top": 8, "margin-left": 12, "margin-right": 12, "reload_style_on_change": True,
        "modules-left": ["group/start"],
        "modules-center": ["clock"],
        "modules-right": ["group/status"],
        "group/start": {"orientation": "horizontal", "modules": ["image#logo", "hyprland/workspaces"]},
        "group/status": {"orientation": "horizontal",
                         "modules": ["custom/vpn", "network", "pulseaudio", "battery", "tray", "custom/power"]},
        # PNG rendered from the vector at 2x (an SVG here made Waybar hit a Wayland protocol error)
        "image#logo": {"path": f"{d}/icon-bar.png", "size": 22, "on-click": "cisa-menu",
                       "tooltip": False},
        "hyprland/workspaces": {"format": "{name}", "on-click": "activate", "sort-by-number": True,
                                "persistent-workspaces": {"*": 5}},
        "clock": {"format": "{:%a %d %b   %H:%M}", "tooltip-format": "<tt>{calendar}</tt>",
                  "calendar": {"mode": "month", "format": {"today": f"<span color='{t['ACCENT']}'><b>{{}}</b></span>"}},
                  "on-click": "kitty --class cisa-cal -e cisa-cal"},
        "custom/vpn": {"exec": "cisa-vpn", "return-type": "json", "interval": 5, "on-click": "cisa-vpn --copy",
                       "tooltip": True},
        "network": {"format-wifi": I["wifi"], "format-ethernet": I["eth"], "format-disconnected": I["off"],
                    "tooltip-format": "{ifname}  {ipaddr}/{cidr}", "tooltip-format-wifi": "{essid}  {signalStrength}%  {ipaddr}",
                    "on-click": "nm-connection-editor"},
        "pulseaudio": {"format": "{icon}  {volume}", "format-muted": I["mute"],
                       "format-icons": {"default": [I["mute"], I["vol"], I["vol"]]},
                       "on-click": "pavucontrol-qt", "scroll-step": 5, "tooltip": False},
        "battery": {"format": "{icon}  {capacity}", "format-charging": I["plug"] + "  {capacity}",
                    "format-icons": I["bat"], "states": {"warning": 25, "critical": 12}},
        "tray": {"spacing": 10, "icon-size": 14},
        "custom/power": {"format": I["power"], "tooltip": False, "on-click": "cisa-power"},
    }
    return {"waybar/config.jsonc": "// CISA Rice Waybar (generated)\n" + json.dumps(cfg, indent=2, ensure_ascii=False),
            "waybar/style.css": waybar_css(t)}


def waybar_css(t):
    S = surface(t)
    r = S["radius"]
    acc = t["ACCENT"] if t["STYLE"] != "blueprint" else "#f2f2f2"
    sheen = f"background-image: {S['sheen']};" if S["sheen"] != "none" else ""
    shadow = f"box-shadow: {S['shadow']};" if S["shadow"] != "none" else ""
    return f"""/* CISA Rice Waybar: {t['NAME']} ({t['STYLE']}). Three floating islands. */
* {{
    font-family: "{FONT}", "{ICON_FONT}", sans-serif;
    font-size: 12px;
    font-weight: 600;
    min-height: 0;
    border: none;
    border-radius: 0;
    box-shadow: none;
    text-shadow: none;
}}
window#waybar {{ background: transparent; color: {S['fg']}; }}
tooltip {{ background: {S['bg_solid']}; border: 1px solid {S['border']}; border-radius: {r}px; }}
tooltip label {{ color: {S['fg']}; font-weight: 500; padding: 2px 4px; }}

/* islands */
#start, #clock, #status {{
    background-color: {S['bg']};
    {sheen}
    border: {S['bw']}px solid {S['border']};
    border-radius: {r}px;
    {shadow}
    margin: 0 2px;
}}
#start {{ padding: 0 8px 0 12px; }}
#status {{ padding: 0 6px; }}
#clock {{ padding: 0 18px; color: {S['fg']}; letter-spacing: 1px; }}

/* CISA mark opens the menu */
#image.logo {{ padding: 0 10px 0 0; }}

/* workspaces: 8px dots (34px bar - 2px border - 2x12px margin), the active one stretches into a pill */
#workspaces {{ padding: 0 2px; }}
#workspaces button {{
    min-width: 8px;
    min-height: 8px;
    padding: 0;
    margin: 12px 4px;
    font-size: 0;
    color: transparent;
    background-color: {rgba(S['fg'] if S['fg'].startswith('#') else '#ffffff', .30)};
    border-radius: 999px;
    transition: all 0.2s ease-in-out;
}}
#workspaces button.empty {{ background-color: {rgba(S['fg'] if S['fg'].startswith('#') else '#ffffff', .14)}; }}
#workspaces button:hover {{ background-color: {rgba(S['fg'] if S['fg'].startswith('#') else '#ffffff', .6)}; }}
#workspaces button.active {{ min-width: 26px; background-color: {acc}; }}
#workspaces button.urgent {{ background-color: {t['RED']}; }}

/* status icons */
#custom-vpn, #network, #pulseaudio, #battery, #tray, #custom-power {{
    padding: 0 10px;
    color: {S['fg']};
    border-radius: {max(r - 6, 0)}px;
    margin: 5px 0;
}}
#network:hover, #pulseaudio:hover, #custom-power:hover, #custom-vpn:hover {{ background-color: {S['hover']}; }}
#custom-power {{ color: {S['muted']}; }}
#custom-power:hover {{ color: {t['RED']}; }}
#pulseaudio.muted, #network.disconnected {{ color: {S['muted']}; }}
#battery.warning:not(.charging) {{ color: {t['YELLOW']}; }}
#battery.critical:not(.charging) {{ color: {t['RED']}; }}
#tray menu {{ background: {S['bg_solid']}; color: {S['fg']}; border: 1px solid {S['border']}; }}

/* lab VPN: a dim shield when off; an accent pill with your IP when connected */
#custom-vpn.off {{ color: {S['muted']}; }}
#custom-vpn.on {{ background-color: {acc}; color: {on(acc)}; margin: 5px 4px; padding: 0 12px; }}
"""


# --------------------------------------------------------------------------- launcher, power menu, notifications

def fuzzel(t, d):
    """fuzzel is used for small pickers (shortcuts, clipboard, themes); styled like the menu card."""
    s = t["STYLE"]
    a = lambda h, al: h.lstrip("#") + f"{round(al * 255):02x}"
    S = surface(t)
    bg = {"glass": a("#10162c", .88), "oled": a("#000000", 1), "blueprint": a("#050505", .96)}.get(s, a(t["SURFACE"], .97))
    fg = "#ffffff" if s == "glass" else ("#f2f2f2" if s == "blueprint" else t["FG"])
    border = {"glass": a("#ffffff", .22), "oled": a(t["LINE"], 1), "blueprint": a("#ffffff", .85)}.get(s, a(t["FG"], .14))
    sel = {"glass": a("#ffffff", .14), "oled": a("#12161d", 1), "blueprint": a("#f2f2f2", 1)}.get(s, a(t["FG"], .10))
    return {"fuzzel/fuzzel.ini": f"""# CISA Rice pickers ({t['NAME']}), styled like the CISA menu
[main]
font={FONT}:size=12,{ICON_FONT}:size=12
prompt="{I['search']}   "
placeholder=Search
icon-theme={t['ICONS']}
icons-enabled=yes
terminal=kitty -e
layer=overlay
anchor=top
y-margin=64
width=56
lines=10
horizontal-pad=24
vertical-pad=20
inner-pad=14
line-height=28
image-size-ratio=0.5

[colors]
background={bg}
text={a(fg, .92)}
prompt={a(t['MUTED'] if s != 'glass' else '#ffffff', 1)}
placeholder={a(t['MUTED'], 1)}
input={a(fg, 1)}
match={a(t['ACCENT'] if s != 'blueprint' else '#ffffff', 1)}
selection={sel}
selection-text={a('#050505' if s == 'blueprint' else fg, 1)}
selection-match={a(t['ACCENT'] if s != 'blueprint' else '#000000', 1)}
border={border}

[border]
width=1
radius={S['radius']}
"""}


def menu(t, d):
    """Stylesheet for cisa-menu (bin/cisa-menu), the start menu / app launcher."""
    S = surface(t)
    s, r = t["STYLE"], S["radius"]
    fg = S["fg"]
    acc = t["ACCENT"] if s != "blueprint" else "#f2f2f2"
    card_bg = {"glass": "rgba(16, 22, 44, 0.62)", "oled": "#000000", "blueprint": "#050505"}.get(s, rgba(t["SURFACE"], .97))
    backdrop = {"oled": "rgba(0,0,0,0.65)", "glass": "rgba(0,0,0,0.18)"}.get(s, "rgba(0,0,0,0.32)" if t["DARK"] else "rgba(10,20,40,0.18)")
    sheen = f"background-image: {S['sheen']};" if S["sheen"] != "none" else ""
    shadow = "box-shadow: 0 24px 60px rgba(0,0,0,0.45);" if s not in ("oled", "blueprint") else ""
    tile_r = max(r - 4, 0)
    return {"cisa-menu/style.css": f"""/* CISA menu ({t['NAME']}, {s}) - generated by CISA Rice */
* {{ font-family: "{FONT}", sans-serif; }}
window.backdrop {{ background-color: {backdrop}; }}

.card {{
    background-color: {card_bg};
    {sheen}
    border: 1px solid {S['border']};
    border-radius: {r + 4 if r else 0}px;
    padding: 22px 24px 14px 24px;
    {shadow}
    color: {fg};
}}

.header {{ margin-bottom: 18px; }}
.greeting {{ font-size: 17px; font-weight: 700; color: {fg}; }}
.sub {{ font-size: 11px; color: {S['muted']}; }}

entry.search {{
    background-color: {S['field']};
    background-image: none;
    color: {fg};
    caret-color: {acc};
    border: 1px solid {S['border']};
    border-radius: {max(r - 2, 0)}px;
    padding: 10px 14px;
    min-height: 22px;
    font-size: 13px;
    box-shadow: none;
}}
entry.search:focus {{ border-color: {acc}; }}
entry.search image {{ color: {S['muted']}; }}

.section {{
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 2px;
    color: {S['muted']};
    margin: 20px 4px 10px 4px;
}}

button {{ background-image: none; box-shadow: none; text-shadow: none; -gtk-icon-shadow: none; }}

.tile {{
    background-color: transparent;
    border: 1px solid transparent;
    border-radius: {tile_r}px;
    padding: 12px 4px 10px 4px;
    color: {fg};
    font-size: 11px;
    transition: all 120ms ease-out;
}}
.tile:hover {{ background-color: {S['hover']}; border-color: {S['border']}; }}
.tile:active {{ background-color: {S['active']}; }}

.chip {{
    background-color: {S['field']};
    border: 1px solid {S['border']};
    border-radius: 999px;
    padding: 6px 16px;
    color: {fg};
    font-size: 12px;
    font-weight: 600;
}}
.chip:hover {{ border-color: {acc}; color: {acc}; }}

list.results, list.results row {{ background-color: transparent; }}
.row {{ border-radius: {tile_r}px; padding: 8px 12px; margin: 1px 0; color: {fg}; }}
.row:selected, .row:hover {{ background-color: {S['active']}; }}
.row:selected .name {{ color: {acc if s != 'blueprint' else '#050505'}; }}
{'.row:selected { background-color: #f2f2f2; } .row:selected .desc { color: #3a3a3a; }' if s == 'blueprint' else ''}
.name {{ font-size: 13px; font-weight: 600; }}
.desc {{ font-size: 11px; color: {S['muted']}; }}
scrollbar {{ background: transparent; border: none; }}
scrollbar slider {{ background-color: {S['border']}; border-radius: 999px; min-width: 4px; }}

.footer {{ border-top: 1px solid {S['border']}; margin-top: 18px; padding-top: 10px; }}
.who {{ font-size: 11px; color: {S['muted']}; }}
.icon-btn {{
    background-color: transparent;
    border: none;
    border-radius: {max(r - 4, 0)}px;
    padding: 7px;
    color: {S['muted']};
    min-width: 0;
    min-height: 0;
}}
.icon-btn:hover {{ background-color: {S['hover']}; color: {fg}; }}
tooltip {{ background-color: {S['bg_solid']}; border: 1px solid {S['border']}; border-radius: 8px; }}
tooltip label {{ color: {fg}; }}
"""}


def wlogout(t, d):
    s = t["STYLE"]
    fg = "#ffffff" if s in ("glass", "blueprint") else t["FG"]
    actions = (("lock", "loginctl lock-session", "l"), ("logout", "hyprctl dispatch exit", "e"),
               ("suspend", "systemctl suspend", "u"), ("reboot", "systemctl reboot", "r"),
               ("shutdown", "systemctl poweroff", "s"))
    layout = "\n".join(json.dumps({"label": n, "action": a, "text": n.capitalize(), "keybind": k})
                       for n, a, k in actions)
    card_bg = {"glass": "rgba(255,255,255,0.08)", "oled": "#000000", "blueprint": "rgba(0,0,0,0.85)"}.get(s, rgba(t["BG"], .9))
    hover_bg = {"glass": "rgba(255,255,255,0.18)", "oled": "#0a0c10", "blueprint": "rgba(255,255,255,0.12)"}.get(s, rgba(t["PANEL"], .14))
    css = f"""/* CISA Rice power menu ({t['NAME']}) */
* {{ background-image: none; box-shadow: none; font-family: "{FONT}"; }}
window {{ background-color: {rgba('#000000', .55 if s != 'oled' else 1)}; }}
button {{
    color: {fg};
    background-color: {card_bg};
    border: 2px solid {rgba(fg, .9 if s != 'oled' else .25)};
    border-radius: {max(t['RADIUS'], 14) if s != 'oled' else 6}px;
    margin: 14px;
    background-repeat: no-repeat;
    background-position: center 42%;
    background-size: 22%;
    font-size: 15px;
    font-weight: bold;
}}
button:focus, button:hover {{ background-color: {hover_bg}; border-color: {t['ACCENT']}; color: {t['ACCENT']}; }}
""" + "\n".join(f'#{n} {{ background-image: url("{d}/wlogout/{n}.svg"); }}' for n, _, _ in actions)
    return {"wlogout/layout": layout + "\n", "wlogout/style.css": css}


def wlogout_icons(t):
    """Stroke icons for the power menu, in the theme's text colour."""
    c = "#ffffff" if t["STYLE"] in ("glass", "blueprint") else t["FG"]
    sv = lambda body: (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="96" height="96" fill="none" '
                       f'stroke="{c}" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">{body}</svg>')
    return {
        "lock": sv('<rect x="5" y="11" width="14" height="10" rx="2"/><path d="M8 11V7a4 4 0 0 1 8 0v4"/>'),
        "logout": sv('<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><path d="M16 17l5-5-5-5"/><path d="M21 12H9"/>'),
        "suspend": sv('<path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/>'),
        "reboot": sv('<path d="M3 12a9 9 0 1 0 3-6.7"/><path d="M3 3v6h6"/>'),
        "shutdown": sv('<path d="M12 2v10"/><path d="M18.4 6.6a9 9 0 1 1-12.8 0"/>'),
    }


def swaync(t, d):
    s = t["STYLE"]
    r = 12 if s == "glass" else (0 if s == "oled" else max(t["RADIUS"], 6))
    card = {"glass": "rgba(255,255,255,0.10)", "oled": "#000000"}.get(s, rgba(t["BG"], .95))
    border = {"glass": "rgba(255,255,255,0.30)", "oled": t["LINE"]}.get(s, rgba(t["FG"], .8))
    cfg = {"positionX": "right", "positionY": "top", "layer": "overlay", "control-center-margin-top": 8,
           "control-center-margin-right": 10, "control-center-width": 400, "notification-window-width": 380,
           "timeout": 6, "timeout-low": 4, "timeout-critical": 0, "fit-to-screen": True,
           "widgets": ["title", "dnd", "notifications"],
           "widget-config": {"title": {"text": "Notifications", "clear-all-button": True, "button-text": "clear"},
                             "dnd": {"text": "Do not disturb"}}}
    css = f"""/* CISA Rice notifications ({t['NAME']}) */
* {{ font-family: "{FONT}"; font-size: 13px; }}
.notification-row {{ outline: none; }}
.notification, .control-center {{
    background: {card};
    border: {1 if s in ('oled', 'glass') else 2}px solid {border};
    border-radius: {r}px;
    color: {t['FG']};
}}
.notification {{ padding: 6px; margin: 6px 10px; }}
.notification-content {{ color: {t['FG']}; }}
.summary {{ font-weight: bold; color: {t['FG']}; }}
.body {{ color: {t['MUTED']}; }}
.time {{ color: {t['MUTED']}; }}
.notification.critical {{ border-color: {t['RED']}; }}
.close-button {{ background: {t['ACCENT']}; color: {on(t['ACCENT'])}; border-radius: {r}px; }}
.control-center {{ padding: 10px; }}
.widget-title {{ color: {t['FG']}; font-weight: bold; margin: 6px; }}
.widget-title > button {{ background: transparent; color: {t['FG']}; border: 1px solid {border}; border-radius: {r}px; }}
.widget-dnd {{ color: {t['FG']}; margin: 6px; }}
.widget-dnd > switch {{ background: {rgba(t['FG'], .2)}; border-radius: {r}px; }}
.widget-dnd > switch:checked {{ background: {t['ACCENT']}; }}
"""
    return {"swaync/config.json": json.dumps(cfg, indent=2), "swaync/style.css": css}


# --------------------------------------------------------------------------- terminal & TUI apps

def kitty(t, d):
    c = term_colors(t)
    colors = "\n".join(f"color{i} {v}" for i, v in enumerate(c))
    sel_bg = mix(t["BG"], t["ACCENT"], 30)
    return {"kitty/kitty.conf": f"""# CISA Rice terminal ({t['NAME']})
font_family      {FONT}
bold_font        {FONT} Bold
italic_font      auto
font_size        11
modify_font      cell_height 118%
disable_ligatures cursor

background            {t['BG']}
foreground            {t['FG']}
background_opacity    {t['TERM_OPACITY']}
background_blur       0
dim_opacity           0.8
cursor                {t['ACCENT']}
cursor_text_color     background
cursor_shape          beam
cursor_beam_thickness 1.6
cursor_blink_interval 0.6
cursor_stop_blinking_after 8
cursor_trail          3
cursor_trail_decay    0.08 0.28
selection_background  {sel_bg}
selection_foreground  none
url_color             {t['ACCENT2']}
url_style             curly
{colors}

window_padding_width  14 20
placement_strategy    top-left
hide_window_decorations yes
confirm_os_window_close 0
enable_audio_bell     no
scrollback_lines      10000
mouse_hide_wait       2.0

# minimal tabs: only shown when there is more than one
tab_bar_edge          bottom
tab_bar_style         separator
tab_separator         "  "
tab_bar_min_tabs      2
tab_title_template    " {{index}}  {{title[:24]}} "
active_tab_foreground   {t['ACCENT']}
active_tab_background   {t['BG']}
active_tab_font_style   bold
inactive_tab_foreground {t['MUTED']}
inactive_tab_background {t['BG']}
tab_bar_background      {t['BG']}

shell_integration     enabled no-cursor
allow_remote_control  socket-only
listen_on             unix:@kitty-{{kitty_pid}}
"""}


def btop(t, d):
    lines = {
        "main_bg": "", "main_fg": t["FG"], "title": t["FG"], "hi_fg": t["ACCENT"], "selected_bg": t["ACCENT"],
        "selected_fg": on(t["ACCENT"]), "inactive_fg": t["MUTED"], "graph_text": t["MUTED"], "meter_bg": t["LINE"],
        "proc_misc": t["ACCENT2"], "cpu_box": t["MUTED"], "mem_box": t["MUTED"], "net_box": t["MUTED"],
        "proc_box": t["MUTED"], "div_line": t["LINE"], "temp_start": t["GREEN"], "temp_mid": t["YELLOW"],
        "temp_end": t["RED"], "cpu_start": t["ACCENT2"], "cpu_mid": t["ACCENT"], "cpu_end": t["RED"],
        "free_start": t["GREEN"], "free_mid": t["GREEN"], "free_end": t["GREEN"], "cached_start": t["BLUE"],
        "cached_mid": t["BLUE"], "cached_end": t["BLUE"], "available_start": t["ACCENT2"],
        "available_mid": t["ACCENT2"], "available_end": t["ACCENT2"], "used_start": t["ACCENT"],
        "used_mid": t["ACCENT"], "used_end": t["RED"], "download_start": t["CYAN"], "download_mid": t["BLUE"],
        "download_end": t["ACCENT2"], "upload_start": t["MAGENTA"], "upload_mid": t["ACCENT"],
        "upload_end": t["RED"], "process_start": t["ACCENT2"], "process_mid": t["ACCENT"], "process_end": t["RED"],
    }
    theme = "\n".join(f'theme[{k}]="{v}"' for k, v in lines.items())
    conf = f"""color_theme = "cisa"
theme_background = False
truecolor = True
rounded_corners = {'True' if t['RADIUS'] >= 6 else 'False'}
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1500
"""
    return {"btop/themes/cisa.theme": theme + "\n", "btop/btop.conf": conf}


def cava(t, d):
    return {"cava/config": f"""; CISA Rice audio visualiser ({t['NAME']})
[general]
framerate = 60
bar_width = 2
bar_spacing = 1

[input]
method = pipewire
source = auto

[output]
method = noncurses

[color]
gradient = 1
gradient_count = 3
gradient_color_1 = '{t['ACCENT2']}'
gradient_color_2 = '{t['ACCENT']}'
gradient_color_3 = '{t['FG']}'
"""}


def fastfetch(t, d):
    k = f"38;2;{';'.join(map(str, hex_rgb(t['ACCENT'])))}"
    f = f"38;2;{';'.join(map(str, hex_rgb(t['FG'])))}"
    m = f"38;2;{';'.join(map(str, hex_rgb(t['MUTED'])))}"
    modules = [
        {"type": "title", "format": "{user-name-colored}{at-symbol-colored}{host-name-colored}",
         "color": {"user": k, "at": m, "host": f}},
        {"type": "custom", "format": f"\u001b[{m}m────────────────────────────\u001b[0m"},
        {"type": "custom", "format": f"\u001b[1;{f}mCISA Linux\u001b[0m \u001b[{m}m· hack legally\u001b[0m"},
        # short formats so it fits a half-width terminal without wrapping
        {"type": "os", "key": "  os    ", "format": "{name} {version-id}"},
        {"type": "kernel", "key": "  kernel", "format": "{release}"},
        {"type": "wm", "key": "  wm    ", "format": "{pretty-name} {version}"},
        {"type": "terminal", "key": "  term  ", "format": "{pretty-name}"},
        {"type": "uptime", "key": "  up    "},
        {"type": "cpu", "key": "  cpu   ", "format": "{cores-logical} cores"},
        {"type": "memory", "key": "  mem   ", "format": "{used} / {total}"},
        {"type": "disk", "key": "  disk  ", "folders": "/", "format": "{size-used} / {size-total}"},
        {"type": "localip", "key": "  ip    ", "showIpv6": False, "showPrefixLen": False, "format": "{ipv4}"},
        {"type": "command", "key": "  vpn   ",
         "text": "ip -4 -o addr show tun0 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | grep . || echo 'off'"},
        {"type": "custom", "format": f"  \u001b[{m}mtheme\u001b[0m   {t['NAME'].lower()}"},
        "break", {"type": "colors", "symbol": "square", "paddingLeft": 2},
    ]
    base = {"$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
            "display": {"separator": "  ", "color": {"keys": k}, "key": {"width": 10}}, "modules": modules}
    # "kitty" (not "kitty-direct"): sends the image itself, so fastfetch doesn't query kitty's version,
    # whose late reply can leak into the prompt on slow machines
    # recache: the icon file keeps its path across themes, so don't reuse fastfetch's cached copy
    img = dict(base, logo={"type": "kitty", "source": f"{d}/icon.png", "width": 22, "height": 11, "recache": True,
                            "padding": {"top": 1, "left": 2, "right": 4}})
    ascii_logo = (f"$1   ▄▄██████▄▄\n$1 ▄████▀▀▀▀████▀\n$1████▀      $2▐██▌$1\n$1████       $2▐██▌$1\n"
                  f"$1████▄      $2▐██▌$1\n$1 ▀████▄▄▄▄████▄\n$1   ▀▀██████▀▀\n")
    txt = dict(base, logo={"type": "data", "source": ascii_logo, "color": {"1": f, "2": k},
                           "padding": {"top": 2, "left": 2, "right": 4}})
    return {"fastfetch/kitty.jsonc": json.dumps(img, indent=2, ensure_ascii=False),
            "fastfetch/config.jsonc": json.dumps(txt, indent=2, ensure_ascii=False)}


def starship(t, d):
    return {"starship.toml": f"""# CISA Rice prompt ({t['NAME']}): minimal. Directory + git on the left;
# lab VPN IP and slow-command time on the right. user@host only shows over SSH or as root.
add_newline = true
palette = "cisa"
format = "$username$hostname$directory$git_branch$git_status$python$character"
right_format = "${{custom.vpn}}$cmd_duration"
continuation_prompt = "[·](muted) "

[palettes.cisa]
accent = "{t['ACCENT']}"
accent2 = "{t['ACCENT2']}"
fg = "{t['FG']}"
good = "{t['GREEN']}"
bad = "{t['RED']}"
warn = "{t['YELLOW']}"
muted = "{t['MUTED']}"

[username]
show_always = false
style_user = "muted"
style_root = "bold bad"
format = "[$user]($style)"

[hostname]
ssh_only = true
style = "muted"
format = "[@$hostname]($style) "

[directory]
style = "bold fg"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"
read_only = " ro"
read_only_style = "muted"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = ""
style = "accent2"
format = "[$branch]($style) "

[git_status]
style = "muted"
format = "[$all_status$ahead_behind]($style) "

[python]
style = "muted"
format = "[py $version]($style) "

[cmd_duration]
min_time = 3000
style = "muted"
format = "[$duration]($style)"

[character]
success_symbol = "[❯](bold accent)"
error_symbol = "[❯](bold bad)"

[custom.vpn]
command = "ip -4 -o addr show tun0 | awk '{{print $4}}' | cut -d/ -f1"
when = "ip link show tun0"
shell = ["bash", "--noprofile", "--norc"]
style = "bold good"
format = "[vpn $output]($style)  "
"""}


# --------------------------------------------------------------------------- KDE (Plasma + Qt apps in Hyprland)

def kde_colors(t, scheme_id):
    view, window = (t["BG"], t["SURFACE"]) if t["DARK"] else ("#ffffff", t["BG"])
    button, alt = mix(window, t["FG"], 7), mix(view, t["FG"], 4)
    sel_fg = on(t["ACCENT"])
    rgb = lambda h: ",".join(map(str, hex_rgb(h)))

    def grp(name, bgc, altc, fgc):
        return (f"[{name}]\nBackgroundAlternate={rgb(altc)}\nBackgroundNormal={rgb(bgc)}\n"
                f"DecorationFocus={rgb(t['ACCENT'])}\nDecorationHover={rgb(t['ACCENT2'])}\n"
                f"ForegroundActive={rgb(t['ACCENT2'])}\nForegroundInactive={rgb(t['MUTED'])}\n"
                f"ForegroundLink={rgb(t['ACCENT2'])}\nForegroundNegative={rgb(t['RED'])}\n"
                f"ForegroundNeutral={rgb(t['YELLOW'])}\nForegroundNormal={rgb(fgc)}\n"
                f"ForegroundPositive={rgb(t['GREEN'])}\nForegroundVisited={rgb(t['MAGENTA'])}\n\n")
    return ("[ColorEffects:Disabled]\nColor=" + rgb(window) + "\nColorAmount=0.5\nColorEffect=3\nContrastAmount=0.5\n"
            "ContrastEffect=0\nIntensityAmount=0\nIntensityEffect=0\n\n"
            "[ColorEffects:Inactive]\nChangeSelectionColor=true\nColor=" + rgb(window) + "\nColorAmount=0.025\n"
            "ColorEffect=0\nContrastAmount=0.1\nContrastEffect=0\nEnable=false\nIntensityAmount=0\nIntensityEffect=0\n\n"
            + grp("Colors:Button", button, mix(button, t["FG"], 4), t["FG"])
            + grp("Colors:Complementary", t["BG"], t["SURFACE"], t["FG"])
            + grp("Colors:Header", window, mix(window, t["FG"], 4), t["FG"])
            + grp("Colors:Header][Inactive", view, mix(view, t["FG"], 4), t["MUTED"])
            + grp("Colors:Selection", t["ACCENT"], mix(t["ACCENT"], t["BG"], 15), sel_fg)
            + grp("Colors:Tooltip", window, alt, t["FG"])
            + grp("Colors:View", view, alt, t["FG"])
            + grp("Colors:Window", window, mix(window, t["FG"], 4), t["FG"])
            + f"[General]\nColorScheme={scheme_id}\nName=CISA {t['NAME']}\nshadeSortColumn=true\n\n[KDE]\ncontrast=4\n\n"
            f"[WM]\nactiveBackground={rgb(window)}\nactiveBlend={rgb(t['FG'])}\nactiveForeground={rgb(t['FG'])}\n"
            f"inactiveBackground={rgb(view)}\ninactiveBlend={rgb(t['MUTED'])}\ninactiveForeground={rgb(t['MUTED'])}\n")


def konsole(t):
    c = term_colors(t)
    tbg = t["BG"] if t["DARK"] else "#ffffff"
    rgb = lambda h: ",".join(map(str, hex_rgb(h)))
    out = [f"[Background]\nColor={rgb(tbg)}\n", f"[BackgroundIntense]\nColor={rgb(tbg)}\n"]
    for i in range(8):
        out.append(f"[Color{i}]\nColor={rgb(c[i])}\n")
        out.append(f"[Color{i}Intense]\nColor={rgb(c[i + 8])}\n")
    out += [f"[Foreground]\nColor={rgb(t['FG'])}\n", f"[ForegroundIntense]\nColor={rgb(t['ACCENT2'])}\n",
            f"[General]\nDescription=CISA {t['NAME']}\nOpacity={t['TERM_OPACITY']}\nBlur=true\n"]
    return "\n".join(out)


ALL = (hyprland, hyprlock, hypridle, waybar, fuzzel, menu, wlogout, swaync, kitty, btop, cava, fastfetch, starship)
