"""CISA Rice: generate every app config from a theme palette.

Each function returns {relative path under ~/.config: file content}. The look is
one design language (boxed monospace modules, thin borders, TUI widgets) in four
styles: solid, glass (frosted + glossy), oled (true black, no glow), blueprint
(monochrome, boxed, like the reference rice).
"""
import json

from art import hex_rgb, mix, on, rgba

FONT = "JetBrains Mono"
ICON_FONT = "FontAwesome"          # fonts-font-awesome (4.7) - every glyph below exists there

# Font Awesome 4.7 glyphs
I = {
    "power": "", "apps": "", "brush": "", "cpu": "", "mem": "", "disk": "",
    "temp": "", "wifi": "", "eth": "", "off": "", "vol": "", "mute": "",
    "mic": "", "bat": ["", "", "", "", ""], "plug": "", "shield": "",
    "lock": "", "clock": "", "bell": "", "term": "", "search": "", "key": "",
    "logout": "", "moon": "", "refresh": "", "grid": "",
}


def hy(h, alpha=1.0):
    """Hyprland colour: rgba(rrggbbaa)."""
    return f"rgba({h.lstrip('#')}{round(alpha * 255):02x})"


def term_colors(t):
    if t["DARK"]:
        black, white = mix(t["BG"], "#000000", 35), mix(t["FG"], t["BG"], 12)
        bblack, bwhite = t["MUTED"], t["FG"]
    else:
        black, white = t["FG"], mix(t["BG"], "#000000", 12)
        bblack, bwhite = t["MUTED"], mix(t["BG"], "#000000", 4)
    base = [black, t["RED"], t["GREEN"], t["YELLOW"], t["BLUE"], t["MAGENTA"], t["CYAN"], white]
    bright = [bblack] + [mix(c, "#ffffff" if t["DARK"] else "#000000", 18) for c in base[1:7]] + [bwhite]
    return base + bright


# --------------------------------------------------------------------------- Hyprland

def hyprland(t, d):
    s = t["STYLE"]
    if s == "glass":
        active = f"{hy('#ffffff', .85)} {hy(t['ACCENT'], .55)} {hy('#ffffff', .25)} 45deg"
        inactive = hy("#ffffff", .18)
        blur = "size = 9\n        passes = 4\n        vibrancy = 0.32\n        noise = 0.015\n        brightness = 1.05\n        contrast = 1.0"
        shadow = f"enabled = true\n        range = 28\n        render_power = 3\n        color = {hy('#000000', .45)}"
    elif s == "oled":
        active = hy(t["FG"], .55)
        inactive = hy(t["LINE"])
        blur = "size = 1\n        passes = 1"
        shadow = "enabled = false"
    elif s == "blueprint":
        active = f"{hy('#ffffff')} {hy('#646464')} 45deg"
        inactive = hy("#ffffff", .3)
        blur = "size = 5\n        passes = 3\n        vibrancy = 0.17"
        shadow = f"enabled = true\n        range = 5\n        render_power = 3\n        color = {hy('#1a1a1a')}"
    else:
        active = f"{hy(t['ACCENT'])} {hy(t['FG'], .9)} 45deg"
        inactive = hy(t["LINE"])
        blur = "size = 6\n        passes = 3\n        vibrancy = 0.2"
        shadow = f"enabled = true\n        range = 14\n        render_power = 3\n        color = {hy('#000000', .4 if t['DARK'] else .14)}"
    inactive_op = 1.0 if s == "oled" else max(0.6, float(t["WIN_OPACITY"]) - 0.08)
    return {"hypr/hyprland.conf": f"""# CISA Rice: Hyprland, theme "{t['NAME']}". Generated by cisa-rice; re-run it instead of editing.
# Your own tweaks go in ~/.config/hypr/user.conf (never overwritten).

monitor = , preferred, auto, 1

$terminal = kitty
$files = dolphin
$browser = firefox-esr
$menu = fuzzel

# ---------- autostart
# Waybar can exit if it starts before the session bus/portals are ready: restart it a few times.
# (Theme changes reload it in place with SIGUSR2, so this never spawns duplicates.)
exec-once = sh -c 'for i in 1 2 3 4 5 6; do waybar; sleep 2; done'
exec-once = swaync
exec-once = swaybg -i {d}/wallpaper.png -m fill
exec-once = hypridle
exec-once = systemctl --user start hyprpolkitagent || /usr/libexec/hyprpolkitagent || /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = nm-applet --indicator
exec-once = wl-paste --watch cliphist store
exec-once = cisa-dashboard --first-login
exec = gsettings set org.gnome.desktop.interface color-scheme '{'prefer-dark' if t['DARK'] else 'prefer-light'}'
exec = gsettings set org.gnome.desktop.interface gtk-theme '{'Breeze-Dark' if t['DARK'] else 'Breeze'}'
exec = gsettings set org.gnome.desktop.interface icon-theme '{t['ICONS']}'
exec = gsettings set org.gnome.desktop.interface cursor-theme '{t['CURSOR']}'
exec = gsettings set org.gnome.desktop.interface monospace-font-name '{FONT} 11'
exec = hyprctl setcursor {t['CURSOR']} 24

# ---------- environment
env = XCURSOR_THEME,{t['CURSOR']}
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,kde
env = QT_QPA_PLATFORM,wayland;xcb
env = GDK_BACKEND,wayland,x11
env = MOZ_ENABLE_WAYLAND,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

# ---------- look and feel
general {{
    gaps_in = {t['GAPS_IN']}
    gaps_out = {t['GAPS_OUT']}
    border_size = {t['BORDER']}
    col.active_border = {active}
    col.inactive_border = {inactive}
    resize_on_border = true
    layout = dwindle
}}

decoration {{
    rounding = {t['RADIUS']}
    active_opacity = {t['WIN_OPACITY']}
    inactive_opacity = {inactive_op:.2f}
    dim_inactive = {'false' if s == 'oled' else 'true'}
    dim_strength = 0.06

    shadow {{
        {shadow}
    }}

    blur {{
        enabled = {'true' if t['BLUR'] else 'false'}
        {blur}
        popups = true
    }}
}}

animations {{
    enabled = yes
    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    bezier = quick, 0.15, 0, 0.1, 1
    bezier = almostLinear, 0.5, 0.5, 0.75, 1.0
    animation = global, 1, 10, default
    animation = windows, 1, 4.8, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
    animation = windowsOut, 1, 1.5, almostLinear, popin 87%
    animation = border, 1, 5.4, easeOutQuint
    animation = fade, 1, 3, quick
    animation = layers, 1, 3.8, easeOutQuint
    animation = layersIn, 1, 4, easeOutQuint, fade
    animation = workspaces, 1, 2.2, almostLinear, slidefade 12%
}}

dwindle {{
    preserve_split = true
}}

misc {{
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    background_color = {hy(t['BG'])}
}}

cursor {{
    no_hardware_cursors = true
}}

input {{
    kb_layout = us
    follow_mouse = 1
    touchpad {{
        natural_scroll = false
        tap-to-click = true
    }}
}}

source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/user.conf
""", "hypr/binds.conf": BINDS, "hypr/rules.conf": RULES}


# Windows-familiar where it can be: Super opens the menu, Alt+F4 closes, Alt+Tab switches,
# Win+L locks, Win+E files, Win+V clipboard, Win+Shift+S / Print screenshot, Win+X power menu.
BINDS = """# CISA Rice key bindings (Super = the Windows key). Super+/ shows this list on screen.
$mod = SUPER

bindr = $mod, SUPER_L, exec, pkill fuzzel || fuzzel
bind = $mod, SPACE, exec, pkill fuzzel || fuzzel
bind = $mod, RETURN, exec, kitty
bind = $mod, T, exec, kitty
bind = $mod, E, exec, dolphin
bind = $mod, B, exec, firefox-esr
bind = $mod, D, exec, cisa-dashboard
bind = $mod, SLASH, exec, cisa-keys
bind = $mod SHIFT, T, exec, cisa-theme
bind = $mod, N, exec, swaync-client -t -sw
bind = $mod, V, exec, cisa-clip
bind = $mod, C, exec, hyprpicker -a
bind = $mod, L, exec, loginctl lock-session
bind = $mod, X, exec, cisa-power
bind = $mod, ESCAPE, exec, cisa-power

bind = ALT, F4, killactive
bind = $mod, Q, killactive
bind = $mod, W, togglefloating
bind = $mod, F, fullscreen, 0
bind = $mod, M, fullscreen, 1
bind = $mod, J, layoutmsg, togglesplit
bind = $mod, P, pseudo
bind = ALT, TAB, cyclenext
bind = ALT, TAB, bringactivetotop

bind = , PRINT, exec, cisa-shot region
bind = $mod SHIFT, S, exec, cisa-shot region
bind = SHIFT, PRINT, exec, cisa-shot screen

bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d
bind = $mod SHIFT, left, movewindow, l
bind = $mod SHIFT, right, movewindow, r
bind = $mod SHIFT, up, movewindow, u
bind = $mod SHIFT, down, movewindow, d
binde = $mod CTRL, left, resizeactive, -40 0
binde = $mod CTRL, right, resizeactive, 40 0
binde = $mod CTRL, up, resizeactive, 0 -40
binde = $mod CTRL, down, resizeactive, 0 40

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod, S, togglespecialworkspace, scratch
bind = $mod ALT, S, movetoworkspace, special:scratch
bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up, workspace, e-1
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = , XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPrev, exec, playerctl previous
"""

RULES = """# Window and layer rules (Hyprland 0.53+ syntax).
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol|pavucontrol-qt|nm-connection-editor|blueman-manager)$
windowrule = float on, match:class ^(org.kde.polkit-kde-authentication-agent-1|hyprpolkitagent)$
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = suppress_event maximize, match:class .*

layerrule = blur on, match:namespace ^(waybar|swaync-control-center|swaync-notification-window|launcher|logout_dialog)$
layerrule = ignore_alpha 0.3, match:namespace ^(waybar|swaync-control-center|swaync-notification-window|launcher|logout_dialog)$
"""


def hyprlock(t, d):
    s = t["STYLE"]
    blur = 0 if s in ("oled", "blueprint") else (3 if s == "glass" else 2)
    field_bg = hy("#000000") if s == "oled" else hy(t["BG"], .55 if s == "glass" else .85)
    return {"hypr/hyprlock.conf": f"""# CISA Rice lock screen ({t['NAME']})
general {{
    hide_cursor = true
    grace = 0
}}

background {{
    monitor =
    path = {d}/lock.png
    blur_passes = {blur}
    blur_size = 6
    brightness = {0.85 if t['DARK'] else 1.0}
}}

label {{
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = {hy(t['FG'])}
    font_size = 110
    font_family = {FONT} ExtraBold
    position = 0, 260
    halign = center
    valign = center
}}

label {{
    monitor =
    text = cmd[update:60000] date +"%A, %B %-d" | tr '[:upper:]' '[:lower:]'
    color = {hy(t['MUTED'])}
    font_size = 18
    font_family = {FONT}
    position = 0, 160
    halign = center
    valign = center
}}

input-field {{
    monitor =
    size = 340, 54
    outline_thickness = 2
    rounding = {min(t['RADIUS'], 12)}
    outer_color = {hy(t['FG'], .9)}
    inner_color = {field_bg}
    font_color = {hy(t['FG'])}
    check_color = {hy(t['ACCENT'])}
    fail_color = {hy(t['RED'])}
    fade_on_empty = false
    placeholder_text = <span foreground="##{t['MUTED'].lstrip('#')}">password for $USER</span>
    fail_text = wrong password ($ATTEMPTS)
    dots_size = 0.22
    dots_spacing = 0.35
    font_family = {FONT}
    position = 0, -260
    halign = center
    valign = center
}}

label {{
    monitor =
    text = learn to hack. the legal way.
    color = {hy(t['MUTED'])}
    font_size = 12
    font_family = {FONT}
    position = 0, 40
    halign = center
    valign = bottom
}}
"""}


def hypridle(t, d):
    return {"hypr/hypridle.conf": """# Lock after 5 min, screen off after 10, lock before sleep.
general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
"""}


# --------------------------------------------------------------------------- Waybar

def waybar(t, d):
    cfg = {
        "layer": "top", "position": "top", "height": 34, "spacing": 4, "margin-top": 6, "margin-left": 10,
        "margin-right": 10,
        "modules-left": ["custom/power", "custom/apps", "custom/theme", "group/system", "temperature", "hyprland/window"],
        "modules-center": ["hyprland/workspaces"],
        "modules-right": ["tray", "custom/vpn", "pulseaudio", "network", "battery", "clock"],
        "group/system": {"orientation": "horizontal", "modules": ["cpu", "memory", "disk"]},
        "custom/power": {"format": I["power"], "tooltip-format": "Power menu (Super+X)", "on-click": "cisa-power"},
        "custom/apps": {"format": I["apps"], "tooltip-format": "Apps (Super)", "on-click": "fuzzel"},
        "custom/theme": {"format": I["brush"], "tooltip-format": "Change theme (Super+Shift+T)", "on-click": "cisa-theme"},
        "cpu": {"format": "{usage}% " + I["cpu"], "interval": 3, "on-click": "kitty -e btop"},
        "memory": {"format": "{percentage}% " + I["mem"], "interval": 5, "on-click": "kitty -e btop"},
        "disk": {"format": "{percentage_used}% " + I["disk"], "path": "/", "on-click": "kitty -e btop"},
        "temperature": {"format": "{temperatureC}°C " + I["temp"], "critical-threshold": 85, "on-click": "kitty -e btop"},
        "hyprland/window": {"format": "{title}", "max-length": 42, "separate-outputs": True,
                            "rewrite": {"(.*) — Mozilla Firefox": "$1", "": ""}},
        "hyprland/workspaces": {"format": "{name}", "on-click": "activate", "sort-by-number": True,
                                "persistent-workspaces": {"*": 5}},
        "tray": {"spacing": 10, "icon-size": 15},
        "custom/vpn": {"exec": "cisa-vpn", "return-type": "json", "interval": 5, "on-click": "cisa-vpn --copy",
                       "tooltip": True},
        "pulseaudio": {"format": "{volume}% {icon}", "format-muted": I["mute"] + " muted",
                       "format-icons": {"default": [I["mute"], I["vol"], I["vol"]]},
                       "on-click": "pavucontrol-qt", "scroll-step": 5},
        "network": {"format-wifi": "{essid} {signalStrength}% " + I["wifi"], "format-ethernet": "{ipaddr} " + I["eth"],
                    "format-disconnected": "offline " + I["off"], "tooltip-format": "{ifname}  {ipaddr}/{cidr}  via {gwaddr}",
                    "on-click": "nm-connection-editor"},
        "battery": {"format": "{capacity}% {icon}", "format-charging": "{capacity}% " + I["plug"],
                    "format-icons": I["bat"], "states": {"warning": 30, "critical": 15}},
        "clock": {"format": "{:%a %d  %H:%M}", "tooltip-format": "<tt>{calendar}</tt>",
                  "calendar": {"mode": "month", "format": {"today": f"<span color='{t['ACCENT']}'><b>{{}}</b></span>"}},
                  "on-click": "kitty --class cisa-cal -e cisa-cal"},
    }
    return {"waybar/config.jsonc": "// CISA Rice Waybar (generated)\n" + json.dumps(cfg, indent=2, ensure_ascii=False),
            "waybar/style.css": waybar_css(t)}


def waybar_css(t):
    s, r = t["STYLE"], min(t["RADIUS"], 8) if t["RADIUS"] else 0
    fg, bg = t["FG"], t["BG"]
    # filled modules use the 30% "panel" colour; outlined ones sit on the ground colour
    if s == "glass":
        fill_bg, fill_fg = "rgba(255, 255, 255, 0.16)", "#ffffff"
        line_bg, line_border, line_fg = "rgba(255, 255, 255, 0.07)", "rgba(255, 255, 255, 0.32)", "#ffffff"
        sheen = "background-image: linear-gradient(180deg, rgba(255,255,255,0.22) 0%, rgba(255,255,255,0.04) 55%, rgba(255,255,255,0.0) 100%);"
        shadow = "box-shadow: inset 0 1px 0 rgba(255,255,255,0.35), 0 4px 14px rgba(0,0,0,0.25);"
        r = 12
    elif s == "oled":
        fill_bg, fill_fg = "#000000", fg
        line_bg, line_border, line_fg = "#000000", t["LINE"], fg
        sheen, shadow = "", ""
    elif s == "blueprint":
        fill_bg, fill_fg = "rgba(255, 255, 255, 0.88)", "#000000"
        line_bg, line_border, line_fg = "rgba(0, 0, 0, 0.45)", "#ffffff", "#ffffff"
        sheen, shadow = "", ""
        r = 5
    else:
        fill_bg, fill_fg = rgba(t["PANEL"], .92), on(t["PANEL"]) if t["DARK"] else "#ffffff"
        line_bg, line_border, line_fg = rgba(bg, .72), rgba(fg, .75), fg
        sheen, shadow = "", "box-shadow: 0 2px 8px rgba(0,0,0,0.18);" if t["DARK"] else ""
    border_w = 1 if s in ("oled", "glass") else 2
    return f"""/* CISA Rice Waybar style: {t['NAME']} ({s}) */
* {{
    font-family: "{FONT}", "{ICON_FONT}", sans-serif;
    font-size: 12px;
    font-weight: bold;
    min-height: 0;
    border: none;
    border-radius: 0;
}}

window#waybar {{ background: transparent; color: {fg}; }}
tooltip {{ background: {bg if s != 'glass' else 'rgba(20,27,51,0.92)'}; border: {border_w}px solid {line_border}; border-radius: {r}px; }}
tooltip label {{ color: {fg}; font-weight: normal; }}

/* filled modules */
#custom-power, #custom-apps, #custom-theme, #system, #temperature, #tray, #pulseaudio {{
    background-color: {fill_bg};
    {sheen}
    color: {fill_fg};
    border-radius: {r}px;
    padding: 2px 11px;
    margin: 4px 1px;
    {shadow}
    {'border: 1px solid ' + line_border + ';' if s in ('oled', 'glass') else ''}
}}
#custom-power {{ padding: 2px 12px 2px 11px; }}
#system {{ padding: 0 4px; }}
#cpu, #memory, #disk {{ color: {fill_fg}; padding: 0 7px; }}
#tray menu {{ background: {bg}; color: {fg}; }}

/* outlined modules */
#window, #network, #battery, #clock, #custom-vpn {{
    background-color: {line_bg};
    {sheen if s == 'glass' else ''}
    color: {line_fg};
    border: {border_w}px solid {line_border};
    border-radius: {r}px;
    padding: 1px 11px;
    margin: 4px 1px;
    {shadow if s == 'glass' else ''}
}}
#window {{ margin-left: 10px; font-weight: normal; }}
window#waybar.empty #window {{ background: transparent; border-color: transparent; }}
#clock {{ border-color: {t['ACCENT'] if s == 'solid' else line_border}; }}

/* VPN to the training labs: lit in the accent colour when tun0 is up */
#custom-vpn.on {{ background-color: {t['ACCENT']}; color: {on(t['ACCENT'])}; border-color: {t['ACCENT']}; }}
#custom-vpn.off {{ color: {t['MUTED']}; }}

/* workspaces: pill buttons, the active one stretches (like the reference rice) */
#workspaces {{
    background-color: {'rgba(255,255,255,0.10)' if s == 'glass' else ('#000000' if s == 'oled' else rgba(fg, .14))};
    {'border: 1px solid ' + line_border + ';' if s in ('oled', 'glass') else ''}
    border-radius: {r}px;
    padding: 3px 4px;
    margin: 4px 0;
}}
#workspaces button {{
    min-width: 12px;
    padding: 0 4px;
    margin: 2px 3px;
    color: transparent;
    font-size: 1px;
    background-color: {rgba(fg, .28) if s != 'oled' else t['LINE']};
    border-radius: {max(r - 2, 0)}px;
    transition: all 0.15s ease-in-out;
}}
#workspaces button:hover {{ background-color: {rgba(fg, .6)}; padding: 0 8px; }}
#workspaces button.active {{ background-color: {t['ACCENT'] if s != 'blueprint' else '#d8d9db'}; padding: 0 22px; }}
#workspaces button.urgent {{ background-color: {t['RED']}; }}

#battery.warning:not(.charging) {{ color: {t['YELLOW']}; border-color: {t['YELLOW']}; }}
@keyframes blink {{ to {{ background-color: {t['RED']}; color: #ffffff; }} }}
#battery.critical:not(.charging) {{ animation: blink 0.6s steps(12) infinite alternate; }}
#temperature.critical {{ background-color: {t['RED']}; color: #ffffff; }}
#pulseaudio.muted {{ background-color: {rgba(t['MUTED'], .6)}; color: {fg}; }}
#network.disconnected {{ color: {t['RED']}; border-color: {t['RED']}; }}
"""


# --------------------------------------------------------------------------- launcher, power menu, notifications

def fuzzel(t, d):
    s = t["STYLE"]
    a = lambda h, al: h.lstrip("#") + f"{round(al * 255):02x}"
    bg_alpha = {"glass": .55, "oled": 1.0, "blueprint": .8}.get(s, .94)
    return {"fuzzel/fuzzel.ini": f"""# CISA Rice launcher ({t['NAME']})
[main]
font={FONT}:size=13,{ICON_FONT}:size=13
prompt="{I['search']}  "
placeholder=Search apps
icon-theme={t['ICONS']}
icons-enabled=yes
terminal=kitty -e
layer=overlay
width=46
lines=8
horizontal-pad=22
vertical-pad=18
inner-pad=10
line-height=26
letter-spacing=0
image-size-ratio=0.5

[colors]
background={a(t['BG'], bg_alpha)}
text={a(t['FG'], 1)}
prompt={a(t['FG'], 1)}
placeholder={a(t['MUTED'], 1)}
input={a(t['FG'], 1)}
match={a(t['ACCENT'], 1)}
selection={a('#ffffff' if s == 'blueprint' else (t['PANEL'] if s != 'glass' else '#ffffff'), .92 if s != 'glass' else .22)}
selection-text={a('#000000' if s == 'blueprint' else (t['BG'] if s != 'glass' else '#ffffff'), 1)}
selection-match={a(t['ACCENT_ON_PANEL'] if s not in ('glass', 'blueprint') else t['ACCENT'], 1)}
border={a('#ffffff' if s in ('glass', 'blueprint') else t['FG'], .55 if s == 'glass' else (.35 if s == 'oled' else 1))}

[border]
width={1 if s in ('oled', 'glass') else 2}
radius={t['RADIUS'] if s != 'blueprint' else 8}
"""}


def wlogout(t, d):
    s = t["STYLE"]
    fg = "#ffffff" if s in ("glass", "blueprint") else t["FG"]
    actions = (("lock", "loginctl lock-session", "l"), ("logout", "hyprctl dispatch exit", "e"),
               ("suspend", "systemctl suspend", "u"), ("reboot", "systemctl reboot", "r"),
               ("shutdown", "systemctl poweroff", "s"))
    layout = "\n".join(json.dumps({"label": n, "action": a, "text": n.capitalize(), "keybind": k})
                       for n, a, k in actions)
    card_bg = {"glass": "rgba(255,255,255,0.08)", "oled": "#000000", "blueprint": "rgba(0,0,0,0.85)"}.get(s, rgba(t["BG"], .9))
    hover_bg = {"glass": "rgba(255,255,255,0.18)", "oled": "#0a0c10", "blueprint": "rgba(255,255,255,0.12)"}.get(s, rgba(t["PANEL"], .14))
    css = f"""/* CISA Rice power menu ({t['NAME']}) */
* {{ background-image: none; box-shadow: none; font-family: "{FONT}"; }}
window {{ background-color: {rgba('#000000', .55 if s != 'oled' else 1)}; }}
button {{
    color: {fg};
    background-color: {card_bg};
    border: 2px solid {rgba(fg, .9 if s != 'oled' else .25)};
    border-radius: {max(t['RADIUS'], 14) if s != 'oled' else 6}px;
    margin: 14px;
    background-repeat: no-repeat;
    background-position: center 42%;
    background-size: 22%;
    font-size: 15px;
    font-weight: bold;
}}
button:focus, button:hover {{ background-color: {hover_bg}; border-color: {t['ACCENT']}; color: {t['ACCENT']}; }}
""" + "\n".join(f'#{n} {{ background-image: url("{d}/wlogout/{n}.svg"); }}' for n, _, _ in actions)
    return {"wlogout/layout": layout + "\n", "wlogout/style.css": css}


def wlogout_icons(t):
    """Stroke icons for the power menu, in the theme's text colour."""
    c = "#ffffff" if t["STYLE"] in ("glass", "blueprint") else t["FG"]
    sv = lambda body: (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="96" height="96" fill="none" '
                       f'stroke="{c}" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">{body}</svg>')
    return {
        "lock": sv('<rect x="5" y="11" width="14" height="10" rx="2"/><path d="M8 11V7a4 4 0 0 1 8 0v4"/>'),
        "logout": sv('<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><path d="M16 17l5-5-5-5"/><path d="M21 12H9"/>'),
        "suspend": sv('<path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z"/>'),
        "reboot": sv('<path d="M3 12a9 9 0 1 0 3-6.7"/><path d="M3 3v6h6"/>'),
        "shutdown": sv('<path d="M12 2v10"/><path d="M18.4 6.6a9 9 0 1 1-12.8 0"/>'),
    }


def swaync(t, d):
    s = t["STYLE"]
    r = 12 if s == "glass" else (0 if s == "oled" else max(t["RADIUS"], 6))
    card = {"glass": "rgba(255,255,255,0.10)", "oled": "#000000"}.get(s, rgba(t["BG"], .95))
    border = {"glass": "rgba(255,255,255,0.30)", "oled": t["LINE"]}.get(s, rgba(t["FG"], .8))
    cfg = {"positionX": "right", "positionY": "top", "layer": "overlay", "control-center-margin-top": 8,
           "control-center-margin-right": 10, "control-center-width": 400, "notification-window-width": 380,
           "timeout": 6, "timeout-low": 4, "timeout-critical": 0, "fit-to-screen": True,
           "widgets": ["title", "dnd", "notifications"],
           "widget-config": {"title": {"text": "Notifications", "clear-all-button": True, "button-text": "clear"},
                             "dnd": {"text": "Do not disturb"}}}
    css = f"""/* CISA Rice notifications ({t['NAME']}) */
* {{ font-family: "{FONT}"; font-size: 13px; }}
.notification-row {{ outline: none; }}
.notification, .control-center {{
    background: {card};
    border: {1 if s in ('oled', 'glass') else 2}px solid {border};
    border-radius: {r}px;
    color: {t['FG']};
}}
.notification {{ padding: 6px; margin: 6px 10px; }}
.notification-content {{ color: {t['FG']}; }}
.summary {{ font-weight: bold; color: {t['FG']}; }}
.body {{ color: {t['MUTED']}; }}
.time {{ color: {t['MUTED']}; }}
.notification.critical {{ border-color: {t['RED']}; }}
.close-button {{ background: {t['ACCENT']}; color: {on(t['ACCENT'])}; border-radius: {r}px; }}
.control-center {{ padding: 10px; }}
.widget-title {{ color: {t['FG']}; font-weight: bold; margin: 6px; }}
.widget-title > button {{ background: transparent; color: {t['FG']}; border: 1px solid {border}; border-radius: {r}px; }}
.widget-dnd {{ color: {t['FG']}; margin: 6px; }}
.widget-dnd > switch {{ background: {rgba(t['FG'], .2)}; border-radius: {r}px; }}
.widget-dnd > switch:checked {{ background: {t['ACCENT']}; }}
"""
    return {"swaync/config.json": json.dumps(cfg, indent=2), "swaync/style.css": css}


# --------------------------------------------------------------------------- terminal & TUI apps

def kitty(t, d):
    c = term_colors(t)
    colors = "\n".join(f"color{i} {v}" for i, v in enumerate(c))
    return {"kitty/kitty.conf": f"""# CISA Rice terminal ({t['NAME']})
font_family      {FONT}
bold_font        auto
font_size        11.5
disable_ligatures never

background            {t['BG']}
foreground            {t['FG']}
background_opacity    {t['TERM_OPACITY']}
cursor                {t['ACCENT']}
cursor_text_color     {t['BG']}
cursor_shape          block
selection_background  {t['ACCENT']}
selection_foreground  {on(t['ACCENT'])}
url_color             {t['ACCENT2']}
{colors}

window_padding_width  15
hide_window_decorations yes
confirm_os_window_close 0
enable_audio_bell no
tab_bar_style         powerline
tab_powerline_style   slanted
active_tab_background {t['ACCENT']}
active_tab_foreground {on(t['ACCENT'])}
inactive_tab_background {t['SURFACE']}
inactive_tab_foreground {t['MUTED']}
shell_integration     enabled no-cursor
allow_remote_control  socket-only
listen_on             unix:@kitty-{{kitty_pid}}
"""}


def btop(t, d):
    lines = {
        "main_bg": "", "main_fg": t["FG"], "title": t["FG"], "hi_fg": t["ACCENT"], "selected_bg": t["ACCENT"],
        "selected_fg": on(t["ACCENT"]), "inactive_fg": t["MUTED"], "graph_text": t["MUTED"], "meter_bg": t["LINE"],
        "proc_misc": t["ACCENT2"], "cpu_box": t["MUTED"], "mem_box": t["MUTED"], "net_box": t["MUTED"],
        "proc_box": t["MUTED"], "div_line": t["LINE"], "temp_start": t["GREEN"], "temp_mid": t["YELLOW"],
        "temp_end": t["RED"], "cpu_start": t["ACCENT2"], "cpu_mid": t["ACCENT"], "cpu_end": t["RED"],
        "free_start": t["GREEN"], "free_mid": t["GREEN"], "free_end": t["GREEN"], "cached_start": t["BLUE"],
        "cached_mid": t["BLUE"], "cached_end": t["BLUE"], "available_start": t["ACCENT2"],
        "available_mid": t["ACCENT2"], "available_end": t["ACCENT2"], "used_start": t["ACCENT"],
        "used_mid": t["ACCENT"], "used_end": t["RED"], "download_start": t["CYAN"], "download_mid": t["BLUE"],
        "download_end": t["ACCENT2"], "upload_start": t["MAGENTA"], "upload_mid": t["ACCENT"],
        "upload_end": t["RED"], "process_start": t["ACCENT2"], "process_mid": t["ACCENT"], "process_end": t["RED"],
    }
    theme = "\n".join(f'theme[{k}]="{v}"' for k, v in lines.items())
    conf = f"""color_theme = "cisa"
theme_background = False
truecolor = True
rounded_corners = {'True' if t['RADIUS'] >= 6 else 'False'}
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1500
"""
    return {"btop/themes/cisa.theme": theme + "\n", "btop/btop.conf": conf}


def cava(t, d):
    return {"cava/config": f"""; CISA Rice audio visualiser ({t['NAME']})
[general]
framerate = 60
bar_width = 2
bar_spacing = 1

[input]
method = pipewire
source = auto

[output]
method = noncurses

[color]
gradient = 1
gradient_count = 3
gradient_color_1 = '{t['ACCENT2']}'
gradient_color_2 = '{t['ACCENT']}'
gradient_color_3 = '{t['FG']}'
"""}


def fastfetch(t, d):
    k = f"38;2;{';'.join(map(str, hex_rgb(t['ACCENT'])))}"
    f = f"38;2;{';'.join(map(str, hex_rgb(t['FG'])))}"
    m = f"38;2;{';'.join(map(str, hex_rgb(t['MUTED'])))}"
    modules = [
        {"type": "title", "format": "{user-name-colored}{at-symbol-colored}{host-name-colored}",
         "color": {"user": k, "at": m, "host": f}},
        {"type": "custom", "format": f"\u001b[{m}m────────────────────────────\u001b[0m"},
        {"type": "custom", "format": f"\u001b[1;{f}mCISA Linux\u001b[0m \u001b[{m}m· hack legally\u001b[0m"},
        # short formats so it fits a half-width terminal without wrapping
        {"type": "os", "key": "  os    ", "format": "{name} {version-id}"},
        {"type": "kernel", "key": "  kernel", "format": "{release}"},
        {"type": "wm", "key": "  wm    ", "format": "{pretty-name} {version}"},
        {"type": "terminal", "key": "  term  ", "format": "{pretty-name}"},
        {"type": "uptime", "key": "  up    "},
        {"type": "cpu", "key": "  cpu   ", "format": "{cores-logical} cores"},
        {"type": "memory", "key": "  mem   ", "format": "{used} / {total}"},
        {"type": "disk", "key": "  disk  ", "folders": "/", "format": "{size-used} / {size-total}"},
        {"type": "localip", "key": "  ip    ", "showIpv6": False, "showPrefixLen": False, "format": "{ipv4}"},
        {"type": "command", "key": "  vpn   ",
         "text": "ip -4 -o addr show tun0 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | grep . || echo 'off'"},
        {"type": "custom", "format": f"  \u001b[{m}mtheme\u001b[0m   {t['NAME'].lower()}"},
        "break", {"type": "colors", "symbol": "square", "paddingLeft": 2},
    ]
    base = {"$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
            "display": {"separator": "  ", "color": {"keys": k}, "key": {"width": 10}}, "modules": modules}
    # "kitty" (not "kitty-direct"): sends the image itself, so fastfetch doesn't query kitty's version,
    # whose late reply can leak into the prompt on slow machines
    # recache: the icon file keeps its path across themes, so don't reuse fastfetch's cached copy
    img = dict(base, logo={"type": "kitty", "source": f"{d}/icon.png", "width": 22, "height": 11, "recache": True,
                            "padding": {"top": 1, "left": 2, "right": 4}})
    ascii_logo = (f"$1   ▄▄██████▄▄\n$1 ▄████▀▀▀▀████▀\n$1████▀      $2▐██▌$1\n$1████       $2▐██▌$1\n"
                  f"$1████▄      $2▐██▌$1\n$1 ▀████▄▄▄▄████▄\n$1   ▀▀██████▀▀\n")
    txt = dict(base, logo={"type": "data", "source": ascii_logo, "color": {"1": f, "2": k},
                           "padding": {"top": 2, "left": 2, "right": 4}})
    return {"fastfetch/kitty.jsonc": json.dumps(img, indent=2, ensure_ascii=False),
            "fastfetch/config.jsonc": json.dumps(txt, indent=2, ensure_ascii=False)}


def starship(t, d):
    return {"starship.toml": f"""# CISA Rice prompt ({t['NAME']}). Shows your lab VPN IP when tun0 is up.
add_newline = true
palette = "cisa"
format = \"\"\"[┌](muted)[\\\\[](muted)$username[@](muted)$hostname[\\\\]](muted)[─](muted)[\\\\[](muted)$directory[\\\\]](muted)$git_branch$git_status$python${{custom.vpn}}$cmd_duration
[└](muted)$character\"\"\"

[palettes.cisa]
accent = "{t['ACCENT']}"
accent2 = "{t['ACCENT2']}"
fg = "{t['FG']}"
good = "{t['GREEN']}"
bad = "{t['RED']}"
warn = "{t['YELLOW']}"
muted = "{t['MUTED']}"

[username]
show_always = true
style_user = "bold accent"
style_root = "bold bad"
format = "[$user]($style)"

[hostname]
ssh_only = false
style = "bold fg"
format = "[$hostname]($style)"

[directory]
style = "bold accent2"
truncation_length = 4
read_only = " ro"
format = "[$path]($style)[$read_only]($read_only_style)"

[git_branch]
style = "bold warn"
format = " [$branch]($style)"

[git_status]
style = "warn"
format = "[ $all_status$ahead_behind]($style)"

[python]
style = "warn"
format = " [py $version]($style)"

[cmd_duration]
style = "muted"
format = " [$duration]($style)"

[character]
success_symbol = "[\\\\$](bold accent)"
error_symbol = "[\\\\$](bold bad)"

[custom.vpn]
command = "ip -4 -o addr show tun0 | awk '{{print $4}}' | cut -d/ -f1"
when = "ip link show tun0"
shell = ["bash", "--noprofile", "--norc"]
style = "bold good"
format = " [vpn $output]($style)"
"""}


# --------------------------------------------------------------------------- KDE (Plasma + Qt apps in Hyprland)

def kde_colors(t, scheme_id):
    view, window = (t["BG"], t["SURFACE"]) if t["DARK"] else ("#ffffff", t["BG"])
    button, alt = mix(window, t["FG"], 7), mix(view, t["FG"], 4)
    sel_fg = on(t["ACCENT"])
    rgb = lambda h: ",".join(map(str, hex_rgb(h)))

    def grp(name, bgc, altc, fgc):
        return (f"[{name}]\nBackgroundAlternate={rgb(altc)}\nBackgroundNormal={rgb(bgc)}\n"
                f"DecorationFocus={rgb(t['ACCENT'])}\nDecorationHover={rgb(t['ACCENT2'])}\n"
                f"ForegroundActive={rgb(t['ACCENT2'])}\nForegroundInactive={rgb(t['MUTED'])}\n"
                f"ForegroundLink={rgb(t['ACCENT2'])}\nForegroundNegative={rgb(t['RED'])}\n"
                f"ForegroundNeutral={rgb(t['YELLOW'])}\nForegroundNormal={rgb(fgc)}\n"
                f"ForegroundPositive={rgb(t['GREEN'])}\nForegroundVisited={rgb(t['MAGENTA'])}\n\n")
    return ("[ColorEffects:Disabled]\nColor=" + rgb(window) + "\nColorAmount=0.5\nColorEffect=3\nContrastAmount=0.5\n"
            "ContrastEffect=0\nIntensityAmount=0\nIntensityEffect=0\n\n"
            "[ColorEffects:Inactive]\nChangeSelectionColor=true\nColor=" + rgb(window) + "\nColorAmount=0.025\n"
            "ColorEffect=0\nContrastAmount=0.1\nContrastEffect=0\nEnable=false\nIntensityAmount=0\nIntensityEffect=0\n\n"
            + grp("Colors:Button", button, mix(button, t["FG"], 4), t["FG"])
            + grp("Colors:Complementary", t["BG"], t["SURFACE"], t["FG"])
            + grp("Colors:Header", window, mix(window, t["FG"], 4), t["FG"])
            + grp("Colors:Header][Inactive", view, mix(view, t["FG"], 4), t["MUTED"])
            + grp("Colors:Selection", t["ACCENT"], mix(t["ACCENT"], t["BG"], 15), sel_fg)
            + grp("Colors:Tooltip", window, alt, t["FG"])
            + grp("Colors:View", view, alt, t["FG"])
            + grp("Colors:Window", window, mix(window, t["FG"], 4), t["FG"])
            + f"[General]\nColorScheme={scheme_id}\nName=CISA {t['NAME']}\nshadeSortColumn=true\n\n[KDE]\ncontrast=4\n\n"
            f"[WM]\nactiveBackground={rgb(window)}\nactiveBlend={rgb(t['FG'])}\nactiveForeground={rgb(t['FG'])}\n"
            f"inactiveBackground={rgb(view)}\ninactiveBlend={rgb(t['MUTED'])}\ninactiveForeground={rgb(t['MUTED'])}\n")


def konsole(t):
    c = term_colors(t)
    tbg = t["BG"] if t["DARK"] else "#ffffff"
    rgb = lambda h: ",".join(map(str, hex_rgb(h)))
    out = [f"[Background]\nColor={rgb(tbg)}\n", f"[BackgroundIntense]\nColor={rgb(tbg)}\n"]
    for i in range(8):
        out.append(f"[Color{i}]\nColor={rgb(c[i])}\n")
        out.append(f"[Color{i}Intense]\nColor={rgb(c[i + 8])}\n")
    out += [f"[Foreground]\nColor={rgb(t['FG'])}\n", f"[ForegroundIntense]\nColor={rgb(t['ACCENT2'])}\n",
            f"[General]\nDescription=CISA {t['NAME']}\nOpacity={t['TERM_OPACITY']}\nBlur=true\n"]
    return "\n".join(out)


ALL = (hyprland, hyprlock, hypridle, waybar, fuzzel, wlogout, swaync, kitty, btop, cava, fastfetch, starship)
